### ISSUE TITLE
[auth_error] => 1

### ISSUE THREAD

**Issue by LGZACRO** [rdolgushin/payeer#1]
Hello, what does this error mean [auth_error] => 1 ?

**Comment by rdolgushin** [comment]
This error means that all right, but your authentication request failed.
If the account details are correct, this may be due to the fact that you need to specify in the user profile API correct IP address from which the request.

**Comment by LGZACRO** [comment]
Well the problem is that I hosted my website at ipage.com, and I want to make payouts there by clicking the link, so in payeer api, I typed server in which I am hosting my website, ip address. What is wrong with that? Why there could be an error?

**Comment by rdolgushin** [comment]
Well, then questions:
1. You are using version 0.0.2?
2. It is not clear whether this error occurs when testing on the server or on the local machine?

**Comment by rdolgushin** [comment]
It is possible, that this Payeer API client for Node.js working wrong. But there is a simple way to check it - use `curl` to make auth request to API, for example:

``` bash
$ curl -X POST https://payeer.com/ajax/api/api.php -d 'account=P111111&apiId=222222&apiPass=3333333&language=en'
```

This command with right account data must return response `{"auth_error":"0"}`.

**Comment by LGZACRO** [comment]
Strange thing, I got 2 errors before payout was successful, any ideas? Can You fix this? Because those errors and then successful payout means that the problem is from payeer.com side.

**Comment by LGZACRO** [comment]
I got also this error:

A PHP Error was encountered

Severity: Notice

Message: Undefined index: auth_error

Filename: libraries/cpayeer.php

Line Number: 30

**Comment by rdolgushin** [comment]
> Strange thing, I got 2 errors before payout was successful, any ideas? Can You fix this? Because those errors and then successful payout means that the problem is from payeer.com side.

Yes, it happens. Somethimes I get error with message 'Please try later'. I think this is the result of heavy workload of service. That's that. But it is not a big problem. This is solved by retry. You should be ready to this in anyway with any payment service.

> I got also this error:
> 
> A PHP Error was encountered

I guess that you are using original PHP version of library, developed by payeer.com, but here I represents my homegrown port of this library to Node.js

I think you would be better to apply to official support. They work pretty fast.
https://payeer.com/en/account/support/

**Comment by LGZACRO** [comment]
Well I asked support about this error, they simply closes ticket without answering, I opened ticked maybe 3 times, everyone was closed without answering.... How do You think, what should I do to avoid this error?

**Comment by rdolgushin** [comment]
Hmmm... I guess that support team serve users only in Russian language :-(

> Message: Undefined index: auth_error
> 
> Filename: libraries/cpayeer.php
> 
> Line Number: 30

Looks like you have empty response. You can view more information by uncommenting lines  72 and 74 in `cpayeer.php`:

> 71     $content = curl_exec($handler);
> 72     //print_r($content);
> 73     $arRequest = curl_getinfo($handler);
> 74     //print_r($arRequest);
> 75     curl_close($handler);

**Comment by LGZACRO** [comment]
They respond in English too. Everything is fine now. Problem was with IP address. The very strange thing You know, I typed the dedicated IP of the server of my website, but I still got an error, I contacted support and they gave me unknown IP with which API works fine. How is that possible? How can I get those IP by my self? They didn't answered these questions. Any ideas?

**Comment by LGZACRO** [comment]
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
I've found out! They used not servers IP, they used NAMESERVER IP!
Payeer.com FOR API USES NAMESERVER IP, NOT YOUR HOSTING SERVER IP!! (This is for guys who worked hard to find this out. I spent 2 days to find this out)

**Comment by rdolgushin** [comment]
Congratulations! :-)
